### ISSUE TITLE
Problem with relative imports and Installer class

### ISSUE THREAD

**Issue by hvignolo87** [hvignolo87/tito#3]
When running main.py with not all packages installed, the following error occurs:
```
Traceback (most recent call last):
File "C:\BOT\tito\BOT\modules\Browser.py", line 6, in <module>
from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "C:\BOT\tito\BOT\main.py", line 12, in <module>
from modules import *
File "C:\BOT\tito\BOT\modules\__init__.py", line 2, in <module>
from .Browser import Browser
File "C:\BOT\tito\BOT\modules\Browser.py", line 9, in <module>
Installer('selenium', True).install()
NameError: name 'Installer' is not defined
```

**Comment by hvignolo87** [comment]
It was a problem with the relative imports in the Browser module and a bug in line 49 of Installer.py. Fixed and working.
